export {
  createAuthClientPlugins,
  createAuthServerPlugins,
  defineAuthConfig,
  type AuthAccessStatements,
  type AuthBrowserConfig,
  type AuthRole,
  type AuthRoleConfig,
  type AuthRoleMap,
  type AuthRouteConfig,
  type AuthServerPlugin,
  type AnyDefinedAuthConfig,
  type DefineAuthConfigInput,
  type DefinedAuthConfig,
} from './config.js';
export {
  DEFAULT_AUTH_ERROR_MESSAGE,
  extractAuthErrorMessage,
  handleAuthFormSubmit,
  mountAuthForms,
  resolveAuthRedirectTarget,
  type AuthBrowserOptions,
} from './browser.js';
export {
  getAppRolesForUser,
  isAppBannedUser,
  isAppRole,
  userHasAppPermission,
  type AppAuthUser,
  type AppUserFields,
  type AuthPermissionRequest,
} from './permissions.js';
export {
  createSignOutAuthRequest,
  getAuthApiPrefix,
  getLoginPath,
  getLoginRedirectPath,
  getSignOutPath,
  isAdminRoute,
  isAuthApiRoute,
  isProtectedRoute,
  isSignOutApiRoute,
  resolveRouteAccess,
  resolveSignOutRedirectPath,
  shouldRedirectSignOutRequest,
  type RouteAccessContext,
  type RouteAccessDecision,
} from './routes.js';
export {
  buildAuthOptions,
  createAuth,
  createAuthEmailSenderOptions,
  createAuthFromEnv,
  createBlockAppBannedSessionHook,
  resolveAuthBaseURL,
  resolveAuthSecret,
  type AppAuthSession,
  type AuthRuntimeEnv,
  type BuildAuthOptionsInput,
  type CreateAuthFromEnvInput,
} from './server.js';
